# Generated by Django 4.1.7 on 2023-03-28 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=250)),
                ('image_tested', models.BooleanField(default=False)),
                ('image_lebel', models.CharField(choices=[('Tested', 'Tested'), ('Not Tested', 'Not Tested')], default='Not Tested', max_length=100)),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
